using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace Jot.Services
{
    public class LocalizationService : INotifyPropertyChanged
    {
        private static LocalizationService _instance;
        private Dictionary<string, Dictionary<string, string>> _localizedStrings;

        public static LocalizationService Instance => _instance ??= new LocalizationService();

        public event PropertyChangedEventHandler PropertyChanged;

        private readonly Dictionary<string, string> _supportedLanguages = new()
        {
            { "en", "English" },
            { "es", "Español" },
            { "ca", "Català" },
            { "ast", "Asturianu" }
        };

        public Dictionary<string, string> SupportedLanguages => _supportedLanguages;

        private string _currentLanguage = "en";
        public string CurrentLanguage 
        { 
            get => _currentLanguage;
            private set
            {
                _currentLanguage = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(CurrentLanguage)));
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(CurrentLanguageName)));
            }
        }

        public string CurrentLanguageName => _supportedLanguages.TryGetValue(CurrentLanguage, out var name) ? name : "English";

        private LocalizationService()
        {
            InitializeLocalizedStrings();

            // Establecer idioma inicial (inglés por defecto)
            CurrentLanguage = "en";
        }

        private void InitializeLocalizedStrings()
        {
            _localizedStrings = new Dictionary<string, Dictionary<string, string>>
            {
                ["en"] = new Dictionary<string, string>
                {
                    ["AppTitle"] = "Jot - Modern Note Taking",
                    ["Documents"] = "Documents",
                    ["NewDocument"] = "New Document",
                    ["SaveDocument"] = "Save Document",
                    ["DeleteDocument"] = "Delete Document",
                    ["ExportToHtml"] = "Export to HTML",
                    ["UploadToGitHub"] = "Upload to GitHub",
                    ["Search"] = "Search",
                    ["Language"] = "Language",
                    ["EditMode"] = "Edit",
                    ["PreviewMode"] = "Preview",
                    ["SplitMode"] = "Split",
                    ["VoiceRecognition"] = "Voice Recognition",
                    ["Listening"] = "🎤 Listening... Speak now",
                    ["VoiceRecognitionStopped"] = "🔇 Voice recognition stopped",
                    ["ReadingText"] = "🔊 Reading Text",
                    ["PlayingTextAloud"] = "Playing text aloud...",
                    ["Cancel"] = "Cancel",
                    ["Stop"] = "Stop",
                    ["OK"] = "OK",
                    ["FocusModeActivated"] = "🎯 Focus Mode Activated",
                    ["FocusModeDeactivated"] = "🎯 Focus Mode Deactivated",
                    ["FocusModeDescription"] = "Simplified interface for concentration.\nPress F11 to exit.",
                    ["FocusModeRestored"] = "Complete interface restored.",
                    ["FontSize"] = "📏 Font Size",
                    ["CurrentSize"] = "Current size: {0}pt",
                    ["PomodoroCompleted"] = "🍅 Pomodoro Completed!",
                    ["PomodoroCompletedDescription"] = "Great job! You've completed a 25-minute focus session.\n\nTime for a 5-minute break?",
                    ["StartBreak"] = "Start Break",
                    ["ContinueWriting"] = "Continue Writing",
                    ["Close"] = "Close",
                    ["Warning"] = "Warning",
                    ["Success"] = "Success",
                    ["Error"] = "Error",
                    ["NoDocumentSelected"] = "Please select a document first.",
                    ["AdvancedSearch"] = "Advanced Search",
                    ["SearchFor"] = "Search for:",
                    ["SearchIn"] = "Search in:",
                    ["CurrentDocument"] = "Current Document",
                    ["AllDocuments"] = "All Documents",
                    ["SelectedDocuments"] = "Selected Documents",
                    ["UseRegularExpressions"] = "Use regular expressions",
                    ["WholeWordsOnly"] = "Whole words only",
                    ["FindAndReplace"] = "Find and Replace",
                    ["Find"] = "Find:",
                    ["ReplaceWith"] = "Replace with:",
                    ["CaseSensitive"] = "Case sensitive",
                    ["ReplaceAll"] = "Replace All",
                    ["FindNext"] = "Find Next",
                    ["SearchResult"] = "🔍 Search Result",
                    ["FoundAtPosition"] = "Found at position {0}",
                    ["NotFound"] = "'{0}' not found",
                    ["ReplacementsCompleted"] = "{0} replacements completed",
                    ["DocumentStatistics"] = "📊 Document Statistics",
                    ["CompleteStatistics"] = "📊 Complete Statistics",
                    ["Content"] = "📝 Content:",
                    ["Words"] = "• Words: {0:N0}",
                    ["Characters"] = "• Characters: {0:N0}",
                    ["CharactersNoSpaces"] = "• Characters (no spaces): {0:N0}",
                    ["Lines"] = "• Lines: {0:N0}",
                    ["Paragraphs"] = "• Paragraphs: {0:N0}",
                    ["Sentences"] = "• Sentences: {0:N0}",
                    ["AvgWordsPerSentence"] = "• Average words/sentence: {0}",
                    ["EstimatedTime"] = "⏱️ Estimated Time:",
                    ["ReadingTime"] = "• Reading time: ~{0} min",
                    ["SpeakingTime"] = "• Speaking time: ~{0} min",
                    ["SessionStats"] = "📈 Session Stats:",
                    ["WordsWrittenToday"] = "• Words written today: {0:N0}",
                    ["WordsInSession"] = "• Words in session: {0:N0}",
                    ["NoDocumentSelected"] = "No Document Selected",
                    ["NoDocumentSelectedDescription"] = "Please select or create a document first before uploading to GitHub.",
                    ["Connected"] = "Connected",
                    ["NotConnected"] = "Not Connected",
                    ["LanguageChanged"] = "Language changed to {0}",
                    ["LastModified"] = "Last modified",
                    ["DocumentIndex"] = "Document Index",
                    ["WelcomeToJot"] = "Welcome to Jot",
                    ["CreateFirstDocument"] = "Create your first document to get started",
                    ["CreateNewDocument"] = "Create New Document",
                    ["GitHub"] = "GitHub",
                    ["ConnectGitHub"] = "Connect GitHub",
                    ["UploadCurrent"] = "Upload Current",
                    ["Repositories"] = "Repositories",
                    ["Disconnect"] = "Disconnect",
                    ["ExpandGitHubOptions"] = "Expand GitHub Options",
                    ["DocumentTitle"] = "Document title...",
                    ["SearchDocuments"] = "Search documents...",
                    ["WordsCount"] = "Words: {0}",
                    ["CharactersCount"] = "Characters: {0}",
                    ["ReadingTimeCount"] = "Reading time: {0} min",
                    ["LineColumn"] = "Line {0}, Column {1}",
                    ["ExportingToHtml"] = "Exporting to HTML...",
                    ["ToggleSidebar"] = "Toggle Sidebar",
                    ["QuickUploadToGitHub"] = "Quick Upload to GitHub",
                    ["GitHubSettings"] = "GitHub Settings",
                    ["AIAssistant"] = "AI Assistant",
                    ["PythonCodeExecution"] = "Python Code Execution",
                    ["Close"] = "Close",
                    ["Send"] = "Send",
                    ["EnterYourQuestion"] = "Enter your question...",
                    ["SuggestedQuestions"] = "Suggested questions:",
                    ["ExportDocument"] = "Export to HTML",
                    ["DeleteDocument"] = "Delete",
                    ["UploadDocument"] = "Upload to GitHub",
                    ["ChatbotWelcome"] = "Hi! I'm your document assistant. You can ask me about the content of your documents.",
                    ["SendEmail"] = "Send by Email",
                    ["Send"] = "Send",
                    ["Cancel"] = "Cancel",
                    ["ToEmail"] = "To (Email)",
                    ["FromEmail"] = "From (Email)",
                    ["SendMethod"] = "Send Method",
                    ["DefaultEmailClient"] = "Default Email Client",
                    ["CustomSMTP"] = "Custom SMTP",
                    ["EmailFormat"] = "Format",
                    ["PlainText"] = "Plain Text",
                    ["Password"] = "Password",
                    ["SMTPServer"] = "SMTP Server",
                    ["EmailWarning"] = "For Gmail/Outlook, you may need to enable 'Less secure app access' or use an app password.",
                    ["EmailSentSuccess"] = "Email sent successfully!",
                    ["EmailSentError"] = "Error sending email. Please check your configuration.",
                    ["EnterEmail"] = "Please enter a valid email address.",
                    ["EmailClientOpened"] = "Email client opened successfully. Please complete sending from your email application.",
                    ["EnterCredentials"] = "Please enter your email credentials (email and password).",
                    ["PrintDocument"] = "Print Document",
                    ["PrintError"] = "Error printing document. Please try again.",

                    // 🔄 Version History
                    ["VersionHistory"] = "Version History",
                    ["Versions"] = "Versions",
                    ["Restore"] = "Restore",
                    ["Details"] = "Details",
                    ["Preview"] = "Preview",
                    ["CurrentVersion"] = "Current version",

                    // 🔐 Encryption
                    ["EncryptDocument"] = "Encrypt Document",
                    ["UnlockDocument"] = "Unlock Document",
                    ["ChangePassword"] = "Change Password",
                    ["Encrypt"] = "Encrypt",
                    ["Unlock"] = "Unlock",
                    ["Change"] = "Change",
                    ["CurrentPassword"] = "Current Password",
                    ["NewPassword"] = "New Password",
                    ["ConfirmPassword"] = "Confirm Password",
                    ["PasswordsDoNotMatch"] = "Passwords do not match",
                    ["EncryptDescription"] = "Protect your document with a strong password. Use AES-256 encryption.",
                    ["UnlockDescription"] = "Enter your password to unlock and view this document.",
                    ["ChangePasswordDescription"] = "Change the encryption password for this document.",
                    ["EncryptionWarning"] = "⚠️ Remember your password! There is no way to recover it if you forget it.",
                    ["EncryptionError"] = "Encryption error. Check your password and try again.",
                    ["LockDocument"] = "Lock Document",

                    // ☁️ Cloud Sync
                    ["CloudSync"] = "Cloud Sync",
                    ["CloudProvider"] = "Cloud Provider",
                    ["AutoSync"] = "Auto Sync",
                    ["Enabled"] = "Enabled",
                    ["Disabled"] = "Disabled",
                    ["LastSync"] = "Last sync",
                    ["NeverSynced"] = "Never synced",
                    ["SyncNow"] = "Sync Now",
                    ["Syncing"] = "Syncing...",
                    ["SelectProvider"] = "Select a cloud provider",
                    ["SyncSuccess"] = "Synced successfully",
                    ["SyncError"] = "Sync error",
                    ["CloudSyncInfo"] = "Your document will be synchronized automatically with the selected cloud provider.",

                    // 📸 OCR
                    ["OCR"] = "OCR - Text Recognition",
                    ["OCRDescription"] = "Extract text from images using optical character recognition.",
                    ["OCRLanguage"] = "OCR Language",
                    ["SelectImage"] = "Select Image",
                    ["FromClipboard"] = "From Clipboard",
                    ["ExtractedText"] = "Extracted Text",
                    ["NoTextExtracted"] = "No text extracted yet...",
                    ["ExtractingText"] = "Extracting text...",
                    ["TextExtracted"] = "Text extracted successfully",
                    ["NoImageInClipboard"] = "No image in clipboard",
                    ["NoTextFound"] = "No text found in image",
                    ["InsertText"] = "Insert Text",
                    ["Characters"] = "characters",

                    // 🔗 Document Links
                    ["DocumentLinks"] = "Document Links",
                    ["OutgoingLinks"] = "Outgoing Links",
                    ["Backlinks"] = "Backlinks",
                    ["RelatedDocuments"] = "Related Documents",
                    ["BrokenLinks"] = "Broken Links",
                    ["WikiLinkHelp"] = "Use [[Document Name]] to create links between documents",
                    ["NoLinksFound"] = "No links found",
                    ["NoBacklinksFound"] = "No backlinks found",
                    ["NoRelatedFound"] = "No related documents found",
                    ["DocumentNotFound"] = "Document not found",
                    ["NoBrokenLinks"] = "No broken links",

                    // 📎 Attachments
                    ["Attachments"] = "Attachments",
                    ["AddFile"] = "Add File",
                    ["PasteImage"] = "Paste Image",
                    ["SelectAttachment"] = "Select an attachment to preview",
                    ["NoAttachments"] = "No attachments yet",
                    ["OpenFile"] = "Open File",

                    // 🔧 Tooltips
                    ["TooltipNewDocument"] = "New Document",
                    ["TooltipSave"] = "Save",
                    ["TooltipExportHTML"] = "Export to HTML",
                    ["TooltipPrint"] = "Print Document",
                    ["TooltipPython"] = "Python Code Execution",
                    ["TooltipGitHubUpload"] = "Quick Upload to GitHub",
                    ["TooltipGitHubSettings"] = "GitHub Settings",
                    ["TooltipLanguage"] = "Language / Idioma",
                    ["TooltipAIAssistant"] = "AI Assistant",
                    ["TooltipSendEmail"] = "Send by Email",
                    ["TooltipVersionHistory"] = "Version History",
                    ["TooltipEncryption"] = "Encryption",
                    ["TooltipCloudSync"] = "Cloud Sync",
                    ["TooltipOCR"] = "OCR - Text Recognition",
                    ["TooltipDocumentLinks"] = "Document Links",
                    ["TooltipAttachments"] = "Attachments"
                },
                ["es"] = new Dictionary<string, string>
                {
                    ["AppTitle"] = "Jot - Toma de Notas Moderna",
                    ["Documents"] = "Documentos",
                    ["NewDocument"] = "Nuevo Documento",
                    ["SaveDocument"] = "Guardar Documento",
                    ["DeleteDocument"] = "Eliminar Documento",
                    ["ExportToHtml"] = "Exportar a HTML",
                    ["UploadToGitHub"] = "Subir a GitHub",
                    ["Search"] = "Buscar",
                    ["Language"] = "Idioma",
                    ["EditMode"] = "Editar",
                    ["PreviewMode"] = "Vista Previa",
                    ["SplitMode"] = "Dividir",
                    ["VoiceRecognition"] = "Reconocimiento de Voz",
                    ["Listening"] = "🎤 Escuchando... Habla ahora",
                    ["VoiceRecognitionStopped"] = "🔇 Reconocimiento de voz detenido",
                    ["ReadingText"] = "🔊 Leyendo Texto",
                    ["PlayingTextAloud"] = "Reproduciendo texto en voz alta...",
                    ["Cancel"] = "Cancelar",
                    ["Stop"] = "Detener",
                    ["OK"] = "Aceptar",
                    ["FocusModeActivated"] = "🎯 Modo Enfoque Activado",
                    ["FocusModeDeactivated"] = "🎯 Modo Enfoque Desactivado",
                    ["FocusModeDescription"] = "Interfaz simplificada para concentración.\nPresiona F11 para salir.",
                    ["FocusModeRestored"] = "Interfaz completa restaurada.",
                    ["Warning"] = "Advertencia",
                    ["Success"] = "Éxito",
                    ["Error"] = "Error",
                    ["NoDocumentSelected"] = "Por favor selecciona un documento primero.",
                    ["FontSize"] = "📏 Tamaño de Fuente",
                    ["CurrentSize"] = "Tamaño actual: {0}pt",
                    ["PomodoroCompleted"] = "🍅 ¡Pomodoro Completado!",
                    ["PomodoroCompletedDescription"] = "¡Buen trabajo! Has completado una sesión de concentración de 25 minutos.\n\n¿Es hora de un descanso de 5 minutos?",
                    ["StartBreak"] = "Iniciar Descanso",
                    ["ContinueWriting"] = "Continuar Escribiendo",
                    ["Close"] = "Cerrar",
                    ["AdvancedSearch"] = "Búsqueda Avanzada",
                    ["SearchFor"] = "Buscar:",
                    ["SearchIn"] = "Buscar en:",
                    ["CurrentDocument"] = "Documento Actual",
                    ["AllDocuments"] = "Todos los Documentos",
                    ["SelectedDocuments"] = "Documentos Seleccionados",
                    ["UseRegularExpressions"] = "Usar expresiones regulares",
                    ["WholeWordsOnly"] = "Solo palabras completas",
                    ["FindAndReplace"] = "Buscar y Reemplazar",
                    ["Find"] = "Buscar:",
                    ["ReplaceWith"] = "Reemplazar con:",
                    ["CaseSensitive"] = "Distinguir mayúsculas y minúsculas",
                    ["ReplaceAll"] = "Reemplazar Todo",
                    ["FindNext"] = "Buscar Siguiente",
                    ["SearchResult"] = "🔍 Resultado de Búsqueda",
                    ["FoundAtPosition"] = "Encontrado en posición {0}",
                    ["NotFound"] = "'{0}' no encontrado",
                    ["ReplacementsCompleted"] = "Se realizaron {0} reemplazos",
                    ["DocumentStatistics"] = "📊 Estadísticas del Documento",
                    ["CompleteStatistics"] = "📊 Estadísticas Completas",
                    ["Content"] = "📝 Contenido:",
                    ["Words"] = "• Palabras: {0:N0}",
                    ["Characters"] = "• Caracteres: {0:N0}",
                    ["CharactersNoSpaces"] = "• Caracteres (sin espacios): {0:N0}",
                    ["Lines"] = "• Líneas: {0:N0}",
                    ["Paragraphs"] = "• Párrafos: {0:N0}",
                    ["Sentences"] = "• Oraciones: {0:N0}",
                    ["AvgWordsPerSentence"] = "• Promedio palabras/oración: {0}",
                    ["EstimatedTime"] = "⏱️ Tiempo Estimado:",
                    ["ReadingTime"] = "• Tiempo de lectura: ~{0} min",
                    ["SpeakingTime"] = "• Tiempo de oratoria: ~{0} min",
                    ["SessionStats"] = "📈 Estadísticas de Sesión:",
                    ["WordsWrittenToday"] = "• Palabras escritas hoy: {0:N0}",
                    ["WordsInSession"] = "• Palabras en esta sesión: {0:N0}",
                    ["NoDocumentSelected"] = "Ningún Documento Seleccionado",
                    ["NoDocumentSelectedDescription"] = "Por favor selecciona o crea un documento antes de subirlo a GitHub.",
                    ["Connected"] = "Conectado",
                    ["NotConnected"] = "No Conectado",
                    ["LanguageChanged"] = "Idioma cambiado a {0}",
                    ["LastModified"] = "Última modificación",
                    ["DocumentIndex"] = "Índice del Documento",
                    ["WelcomeToJot"] = "Bienvenido a Jot",
                    ["CreateFirstDocument"] = "Crea tu primer documento para comenzar",
                    ["CreateNewDocument"] = "Crear Nuevo Documento",
                    ["GitHub"] = "GitHub",
                    ["ConnectGitHub"] = "Conectar GitHub",
                    ["UploadCurrent"] = "Subir Actual",
                    ["Repositories"] = "Repositorios",
                    ["Disconnect"] = "Desconectar",
                    ["ExpandGitHubOptions"] = "Expandir Opciones de GitHub",
                    ["DocumentTitle"] = "Título del documento...",
                    ["SearchDocuments"] = "Buscar documentos...",
                    ["WordsCount"] = "Palabras: {0}",
                    ["CharactersCount"] = "Caracteres: {0}",
                    ["ReadingTimeCount"] = "Tiempo de lectura: {0} min",
                    ["LineColumn"] = "Línea {0}, Columna {1}",
                    ["ExportingToHtml"] = "Exportando a HTML...",
                    ["ToggleSidebar"] = "Alternar Barra Lateral",
                    ["QuickUploadToGitHub"] = "Subida Rápida a GitHub",
                    ["GitHubSettings"] = "Configuración de GitHub",
                    ["AIAssistant"] = "Asistente IA",
                    ["PythonCodeExecution"] = "Ejecución de Código Python",
                    ["Close"] = "Cerrar",
                    ["Send"] = "Enviar",
                    ["EnterYourQuestion"] = "Escribe tu pregunta...",
                    ["SuggestedQuestions"] = "Preguntas sugeridas:",
                    ["ExportDocument"] = "Exportar a HTML",
                    ["DeleteDocument"] = "Eliminar",
                    ["UploadDocument"] = "Subir a GitHub",
                    ["ChatbotWelcome"] = "¡Hola! Soy tu asistente de documentos. Puedes preguntarme sobre el contenido de tus documentos.",
                    ["SendEmail"] = "Enviar por Correo",
                    ["Send"] = "Enviar",
                    ["Cancel"] = "Cancelar",
                    ["ToEmail"] = "Para (Email)",
                    ["FromEmail"] = "De (Email)",
                    ["SendMethod"] = "Método de Envío",
                    ["DefaultEmailClient"] = "Cliente de Correo Predeterminado",
                    ["CustomSMTP"] = "SMTP Personalizado",
                    ["EmailFormat"] = "Formato",
                    ["PlainText"] = "Texto Plano",
                    ["Password"] = "Contraseña",
                    ["SMTPServer"] = "Servidor SMTP",
                    ["EmailWarning"] = "Para Gmail/Outlook, puede que necesites activar 'Acceso de apps menos seguras' o usar una contraseña de aplicación.",
                    ["EmailSentSuccess"] = "¡Email enviado correctamente!",
                    ["EmailSentError"] = "Error al enviar email. Por favor verifica tu configuración.",
                    ["EnterEmail"] = "Por favor introduce una dirección de email válida.",
                    ["EmailClientOpened"] = "Cliente de correo abierto correctamente. Por favor completa el envío desde tu aplicación de correo.",
                    ["EnterCredentials"] = "Por favor introduce tus credenciales de email (correo y contraseña).",
                    ["PrintDocument"] = "Imprimir Documento",
                    ["PrintError"] = "Error al imprimir el documento. Por favor intenta de nuevo.",

                    // 🔄 Historial de Versiones
                    ["VersionHistory"] = "Historial de Versiones",
                    ["Versions"] = "Versiones",
                    ["Restore"] = "Restaurar",
                    ["Details"] = "Detalles",
                    ["Preview"] = "Vista Previa",
                    ["CurrentVersion"] = "Versión actual",

                    // 🔐 Cifrado
                    ["EncryptDocument"] = "Cifrar Documento",
                    ["UnlockDocument"] = "Desbloquear Documento",
                    ["ChangePassword"] = "Cambiar Contraseña",
                    ["Encrypt"] = "Cifrar",
                    ["Unlock"] = "Desbloquear",
                    ["Change"] = "Cambiar",
                    ["CurrentPassword"] = "Contraseña Actual",
                    ["NewPassword"] = "Nueva Contraseña",
                    ["ConfirmPassword"] = "Confirmar Contraseña",
                    ["PasswordsDoNotMatch"] = "Las contraseñas no coinciden",
                    ["EncryptDescription"] = "Protege tu documento con una contraseña segura. Usa cifrado AES-256.",
                    ["UnlockDescription"] = "Introduce tu contraseña para desbloquear y ver este documento.",
                    ["ChangePasswordDescription"] = "Cambia la contraseña de cifrado de este documento.",
                    ["EncryptionWarning"] = "⚠️ ¡Recuerda tu contraseña! No hay forma de recuperarla si la olvidas.",
                    ["EncryptionError"] = "Error de cifrado. Verifica tu contraseña e intenta de nuevo.",
                    ["LockDocument"] = "Bloquear Documento",

                    // ☁️ Sincronización
                    ["CloudSync"] = "Sincronización en la Nube",
                    ["CloudProvider"] = "Proveedor de Nube",
                    ["AutoSync"] = "Sincronización Automática",
                    ["Enabled"] = "Habilitado",
                    ["Disabled"] = "Deshabilitado",
                    ["LastSync"] = "Última sincronización",
                    ["NeverSynced"] = "Nunca sincronizado",
                    ["SyncNow"] = "Sincronizar Ahora",
                    ["Syncing"] = "Sincronizando...",
                    ["SelectProvider"] = "Selecciona un proveedor de nube",
                    ["SyncSuccess"] = "Sincronizado correctamente",
                    ["SyncError"] = "Error de sincronización",
                    ["CloudSyncInfo"] = "Tu documento se sincronizará automáticamente con el proveedor de nube seleccionado.",

                    // 📸 OCR
                    ["OCR"] = "OCR - Reconocimiento de Texto",
                    ["OCRDescription"] = "Extrae texto de imágenes usando reconocimiento óptico de caracteres.",
                    ["OCRLanguage"] = "Idioma OCR",
                    ["SelectImage"] = "Seleccionar Imagen",
                    ["FromClipboard"] = "Desde Portapapeles",
                    ["ExtractedText"] = "Texto Extraído",
                    ["NoTextExtracted"] = "Aún no se ha extraído texto...",
                    ["ExtractingText"] = "Extrayendo texto...",
                    ["TextExtracted"] = "Texto extraído correctamente",
                    ["NoImageInClipboard"] = "No hay imagen en el portapapeles",
                    ["NoTextFound"] = "No se encontró texto en la imagen",
                    ["InsertText"] = "Insertar Texto",
                    ["Characters"] = "caracteres",

                    // 🔗 Enlaces
                    ["DocumentLinks"] = "Enlaces del Documento",
                    ["OutgoingLinks"] = "Enlaces Salientes",
                    ["Backlinks"] = "Retroenlaces",
                    ["RelatedDocuments"] = "Documentos Relacionados",
                    ["BrokenLinks"] = "Enlaces Rotos",
                    ["WikiLinkHelp"] = "Usa [[Nombre Documento]] para crear enlaces entre documentos",
                    ["NoLinksFound"] = "No se encontraron enlaces",
                    ["NoBacklinksFound"] = "No se encontraron retroenlaces",
                    ["NoRelatedFound"] = "No se encontraron documentos relacionados",
                    ["DocumentNotFound"] = "Documento no encontrado",
                    ["NoBrokenLinks"] = "No hay enlaces rotos",

                    // 📎 Adjuntos
                    ["Attachments"] = "Archivos Adjuntos",
                    ["AddFile"] = "Agregar Archivo",
                    ["PasteImage"] = "Pegar Imagen",
                    ["SelectAttachment"] = "Selecciona un adjunto para previsualizar",
                    ["NoAttachments"] = "Aún no hay adjuntos",
                    ["OpenFile"] = "Abrir Archivo",

                    // 🔧 Tooltips
                    ["TooltipNewDocument"] = "Nuevo Documento",
                    ["TooltipSave"] = "Guardar",
                    ["TooltipExportHTML"] = "Exportar a HTML",
                    ["TooltipPrint"] = "Imprimir Documento",
                    ["TooltipPython"] = "Ejecución de Código Python",
                    ["TooltipGitHubUpload"] = "Subida Rápida a GitHub",
                    ["TooltipGitHubSettings"] = "Configuración de GitHub",
                    ["TooltipLanguage"] = "Idioma / Language",
                    ["TooltipAIAssistant"] = "Asistente IA",
                    ["TooltipSendEmail"] = "Enviar por Correo",
                    ["TooltipVersionHistory"] = "Historial de Versiones",
                    ["TooltipEncryption"] = "Cifrado",
                    ["TooltipCloudSync"] = "Sincronización en la Nube",
                    ["TooltipOCR"] = "OCR - Reconocimiento de Texto",
                    ["TooltipDocumentLinks"] = "Enlaces del Documento",
                    ["TooltipAttachments"] = "Archivos Adjuntos"
                },
                ["ca"] = new Dictionary<string, string>
                {
                    ["AppTitle"] = "Jot - Presa de Notes Moderna",
                    ["Documents"] = "Documents",
                    ["NewDocument"] = "Nou Document",
                    ["SaveDocument"] = "Desar Document",
                    ["DeleteDocument"] = "Eliminar Document",
                    ["ExportToHtml"] = "Exportar a HTML",
                    ["UploadToGitHub"] = "Pujar a GitHub",
                    ["Search"] = "Cercar",
                    ["Language"] = "Idioma",
                    ["EditMode"] = "Editar",
                    ["PreviewMode"] = "Vista Prèvia",
                    ["SplitMode"] = "Dividir",
                    ["VoiceRecognition"] = "Reconeixement de Veu",
                    ["Listening"] = "🎤 Escoltant... Parla ara",
                    ["VoiceRecognitionStopped"] = "🔇 Reconeixement de veu aturat",
                    ["ReadingText"] = "🔊 Llegint Text",
                    ["PlayingTextAloud"] = "Reproduint text en veu alta...",
                    ["Cancel"] = "Cancel·lar",
                    ["Stop"] = "Aturar",
                    ["OK"] = "D'acord",
                    ["FocusModeActivated"] = "🎯 Mode Concentració Activat",
                    ["FocusModeDeactivated"] = "🎯 Mode Concentració Desactivat",
                    ["FocusModeDescription"] = "Interfície simplificada per a la concentració.\nPrem F11 per sortir.",
                    ["FocusModeRestored"] = "Interfície completa restaurada.",
                    ["Warning"] = "Advertència",
                    ["Success"] = "Èxit",
                    ["Error"] = "Error",
                    ["NoDocumentSelected"] = "Si us plau selecciona un document primer.",
                    ["FontSize"] = "📏 Mida de Lletra",
                    ["CurrentSize"] = "Mida actual: {0}pt",
                    ["PomodoroCompleted"] = "🍅 Pomodoro Completat!",
                    ["PomodoroCompletedDescription"] = "Bona feina! Has completat una sessió de concentració de 25 minuts.\n\nÉs hora d'un descans de 5 minuts?",
                    ["StartBreak"] = "Iniciar Descans",
                    ["ContinueWriting"] = "Continuar Escrivint",
                    ["Close"] = "Tancar",
                    ["AdvancedSearch"] = "Cerca Avançada",
                    ["SearchFor"] = "Cercar:",
                    ["SearchIn"] = "Cercar a:",
                    ["CurrentDocument"] = "Document Actual",
                    ["AllDocuments"] = "Tots els Documents",
                    ["SelectedDocuments"] = "Documents Seleccionats",
                    ["UseRegularExpressions"] = "Usar expressions regulars",
                    ["WholeWordsOnly"] = "Només paraules completes",
                    ["FindAndReplace"] = "Cercar i Reemplaçar",
                    ["Find"] = "Cercar:",
                    ["ReplaceWith"] = "Reemplaçar amb:",
                    ["CaseSensitive"] = "Distingir majúscules i minúscules",
                    ["ReplaceAll"] = "Reemplaçar Tot",
                    ["FindNext"] = "Cercar Següent",
                    ["SearchResult"] = "🔍 Resultat de Cerca",
                    ["FoundAtPosition"] = "Trobat a la posició {0}",
                    ["NotFound"] = "'{0}' no trobat",
                    ["ReplacementsCompleted"] = "Es van realitzar {0} reemplaçaments",
                    ["DocumentStatistics"] = "📊 Estadístiques del Document",
                    ["CompleteStatistics"] = "📊 Estadístiques Completes",
                    ["Content"] = "📝 Contingut:",
                    ["Words"] = "• Paraules: {0:N0}",
                    ["Characters"] = "• Caràcters: {0:N0}",
                    ["CharactersNoSpaces"] = "• Caràcters (sense espais): {0:N0}",
                    ["Lines"] = "• Línies: {0:N0}",
                    ["Paragraphs"] = "• Paràgrafs: {0:N0}",
                    ["Sentences"] = "• Frases: {0:N0}",
                    ["AvgWordsPerSentence"] = "• Mitjana paraules/frase: {0}",
                    ["EstimatedTime"] = "⏱️ Temps Estimat:",
                    ["ReadingTime"] = "• Temps de lectura: ~{0} min",
                    ["SpeakingTime"] = "• Temps d'oratòria: ~{0} min",
                    ["SessionStats"] = "📈 Estadístiques de Sessió:",
                    ["WordsWrittenToday"] = "• Paraules escrites avui: {0:N0}",
                    ["WordsInSession"] = "• Paraules en aquesta sessió: {0:N0}",
                    ["NoDocumentSelected"] = "Cap Document Seleccionat",
                    ["NoDocumentSelectedDescription"] = "Si us plau, selecciona o crea un document abans de pujar-lo a GitHub.",
                    ["Connected"] = "Connectat",
                    ["NotConnected"] = "No Connectat",
                    ["LanguageChanged"] = "Idioma canviat a {0}",
                    ["LastModified"] = "Última modificació",
                    ["DocumentIndex"] = "Índex del Document",
                    ["WelcomeToJot"] = "Benvingut a Jot",
                    ["CreateFirstDocument"] = "Crea el teu primer document per començar",
                    ["CreateNewDocument"] = "Crear Nou Document",
                    ["GitHub"] = "GitHub",
                    ["ConnectGitHub"] = "Connectar GitHub",
                    ["UploadCurrent"] = "Pujar Actual",
                    ["Repositories"] = "Repositoris",
                    ["Disconnect"] = "Desconnectar",
                    ["ExpandGitHubOptions"] = "Expandir Opcions de GitHub",
                    ["DocumentTitle"] = "Títol del document...",
                    ["SearchDocuments"] = "Cercar documents...",
                    ["WordsCount"] = "Paraules: {0}",
                    ["CharactersCount"] = "Caràcters: {0}",
                    ["ReadingTimeCount"] = "Temps de lectura: {0} min",
                    ["LineColumn"] = "Línia {0}, Columna {1}",
                    ["ExportingToHtml"] = "Exportant a HTML...",
                    ["ToggleSidebar"] = "Alternar Barra Lateral",
                    ["QuickUploadToGitHub"] = "Pujada Ràpida a GitHub",
                    ["GitHubSettings"] = "Configuració de GitHub",
                    ["AIAssistant"] = "Assistent IA",
                    ["PythonCodeExecution"] = "Execució de Codi Python",
                    ["Close"] = "Tancar",
                    ["Send"] = "Enviar",
                    ["EnterYourQuestion"] = "Escriu la teva pregunta...",
                    ["SuggestedQuestions"] = "Preguntes suggerides:",
                    ["ExportDocument"] = "Exportar a HTML",
                    ["DeleteDocument"] = "Eliminar",
                    ["UploadDocument"] = "Pujar a GitHub",
                    ["ChatbotWelcome"] = "Hola! Sóc el teu assistent de documents. Pots preguntar-me sobre el contingut dels teus documents.",
                    ["SendEmail"] = "Enviar per Correu",
                    ["Send"] = "Enviar",
                    ["Cancel"] = "Cancel·lar",
                    ["ToEmail"] = "Per a (Email)",
                    ["FromEmail"] = "De (Email)",
                    ["SendMethod"] = "Mètode d'Enviament",
                    ["DefaultEmailClient"] = "Client de Correu Predeterminat",
                    ["CustomSMTP"] = "SMTP Personalitzat",
                    ["EmailFormat"] = "Format",
                    ["PlainText"] = "Text Pla",
                    ["Password"] = "Contrasenya",
                    ["SMTPServer"] = "Servidor SMTP",
                    ["EmailWarning"] = "Per a Gmail/Outlook, pot ser que necessitis activar 'Accés d'apps menys segures' o fer servir una contrasenya d'aplicació.",
                    ["EmailSentSuccess"] = "Email enviat correctament!",
                    ["EmailSentError"] = "Error en enviar email. Si us plau verifica la teva configuració.",
                    ["EnterEmail"] = "Si us plau introdueix una adreça d'email vàlida.",
                    ["EmailClientOpened"] = "Client de correu obert correctament. Si us plau completa l'enviament des de la teva aplicació de correu.",
                    ["EnterCredentials"] = "Si us plau introdueix les teves credencials d'email (correu i contrasenya).",
                    ["PrintDocument"] = "Imprimir Document",
                    ["PrintError"] = "Error en imprimir el document. Si us plau torna-ho a intentar.",

                    // 🔄 Historial de Versions
                    ["VersionHistory"] = "Historial de Versions",
                    ["Versions"] = "Versions",
                    ["Restore"] = "Restaurar",
                    ["Details"] = "Detalls",
                    ["Preview"] = "Vista Prèvia",
                    ["CurrentVersion"] = "Versió actual",

                    // 🔐 Xifrat
                    ["EncryptDocument"] = "Xifrar Document",
                    ["UnlockDocument"] = "Desbloquejar Document",
                    ["ChangePassword"] = "Canviar Contrasenya",
                    ["Encrypt"] = "Xifrar",
                    ["Unlock"] = "Desbloquejar",
                    ["Change"] = "Canviar",
                    ["CurrentPassword"] = "Contrasenya Actual",
                    ["NewPassword"] = "Nova Contrasenya",
                    ["ConfirmPassword"] = "Confirmar Contrasenya",
                    ["PasswordsDoNotMatch"] = "Les contrasenyes no coincideixen",
                    ["EncryptDescription"] = "Protegeix el teu document amb una contrasenya segura. Usa xifratge AES-256.",
                    ["UnlockDescription"] = "Introdueix la teva contrasenya per desbloquejar i veure aquest document.",
                    ["ChangePasswordDescription"] = "Canvia la contrasenya de xifratge d'aquest document.",
                    ["EncryptionWarning"] = "⚠️ Recorda la teva contrasenya! No hi ha manera de recuperar-la si l'oblides.",
                    ["EncryptionError"] = "Error de xifratge. Verifica la teva contrasenya i torna-ho a intentar.",
                    ["LockDocument"] = "Bloquejar Document",

                    // ☁️ Sincronització
                    ["CloudSync"] = "Sincronització al Núvol",
                    ["CloudProvider"] = "Proveïdor de Núvol",
                    ["AutoSync"] = "Sincronització Automàtica",
                    ["Enabled"] = "Activat",
                    ["Disabled"] = "Desactivat",
                    ["LastSync"] = "Última sincronització",
                    ["NeverSynced"] = "Mai sincronitzat",
                    ["SyncNow"] = "Sincronitzar Ara",
                    ["Syncing"] = "Sincronitzant...",
                    ["SelectProvider"] = "Selecciona un proveïdor de núvol",
                    ["SyncSuccess"] = "Sincronitzat correctament",
                    ["SyncError"] = "Error de sincronització",
                    ["CloudSyncInfo"] = "El teu document se sincronitzarà automàticament amb el proveïdor de núvol seleccionat.",

                    // 📸 OCR
                    ["OCR"] = "OCR - Reconeixement de Text",
                    ["OCRDescription"] = "Extreu text d'imatges usant reconeixement òptic de caràcters.",
                    ["OCRLanguage"] = "Idioma OCR",
                    ["SelectImage"] = "Seleccionar Imatge",
                    ["FromClipboard"] = "Des del Porta-retalls",
                    ["ExtractedText"] = "Text Extret",
                    ["NoTextExtracted"] = "Encara no s'ha extret text...",
                    ["ExtractingText"] = "Extraient text...",
                    ["TextExtracted"] = "Text extret correctament",
                    ["NoImageInClipboard"] = "No hi ha imatge al porta-retalls",
                    ["NoTextFound"] = "No s'ha trobat text a la imatge",
                    ["InsertText"] = "Inserir Text",
                    ["Characters"] = "caràcters",

                    // 🔗 Enllaços
                    ["DocumentLinks"] = "Enllaços del Document",
                    ["OutgoingLinks"] = "Enllaços Sortints",
                    ["Backlinks"] = "Retroenllaços",
                    ["RelatedDocuments"] = "Documents Relacionats",
                    ["BrokenLinks"] = "Enllaços Trencats",
                    ["WikiLinkHelp"] = "Usa [[Nom Document]] per crear enllaços entre documents",
                    ["NoLinksFound"] = "No s'han trobat enllaços",
                    ["NoBacklinksFound"] = "No s'han trobat retroenllaços",
                    ["NoRelatedFound"] = "No s'han trobat documents relacionats",
                    ["DocumentNotFound"] = "Document no trobat",
                    ["NoBrokenLinks"] = "No hi ha enllaços trencats",

                    // 📎 Adjunts
                    ["Attachments"] = "Fitxers Adjunts",
                    ["AddFile"] = "Afegir Fitxer",
                    ["PasteImage"] = "Enganxar Imatge",
                    ["SelectAttachment"] = "Selecciona un adjunt per previsualitzar",
                    ["NoAttachments"] = "Encara no hi ha adjunts",
                    ["OpenFile"] = "Obrir Fitxer",

                    // 🔧 Tooltips
                    ["TooltipNewDocument"] = "Nou Document",
                    ["TooltipSave"] = "Desar",
                    ["TooltipExportHTML"] = "Exportar a HTML",
                    ["TooltipPrint"] = "Imprimir Document",
                    ["TooltipPython"] = "Execució de Codi Python",
                    ["TooltipGitHubUpload"] = "Pujada Ràpida a GitHub",
                    ["TooltipGitHubSettings"] = "Configuració de GitHub",
                    ["TooltipLanguage"] = "Idioma / Language",
                    ["TooltipAIAssistant"] = "Assistent IA",
                    ["TooltipSendEmail"] = "Enviar per Correu",
                    ["TooltipVersionHistory"] = "Historial de Versions",
                    ["TooltipEncryption"] = "Xifrat",
                    ["TooltipCloudSync"] = "Sincronització al Núvol",
                    ["TooltipOCR"] = "OCR - Reconeixement de Text",
                    ["TooltipDocumentLinks"] = "Enllaços del Document",
                    ["TooltipAttachments"] = "Fitxers Adjunts"
                },
                ["ast"] = new Dictionary<string, string>
                {
                    ["AppTitle"] = "Jot - Toma de Notes Moderna",
                    ["Documents"] = "Documentos",
                    ["NewDocument"] = "Documentu Nuevu",
                    ["SaveDocument"] = "Guardar Documentu",
                    ["DeleteDocument"] = "Desaniciar Documentu",
                    ["ExportToHtml"] = "Esportar a HTML",
                    ["UploadToGitHub"] = "Xubir a GitHub",
                    ["Search"] = "Guetar",
                    ["Language"] = "Idioma",
                    ["EditMode"] = "Editar",
                    ["PreviewMode"] = "Vista Previa",
                    ["SplitMode"] = "Dividir",
                    ["VoiceRecognition"] = "Reconocimientu de Voz",
                    ["Listening"] = "🎤 Escuchando... Fala agora",
                    ["VoiceRecognitionStopped"] = "🔇 Reconocimientu de voz paráu",
                    ["ReadingText"] = "🔊 Llevendo Testu",
                    ["PlayingTextAloud"] = "Reproduciendo testu en voz alta...",
                    ["Cancel"] = "Encaboxar",
                    ["Stop"] = "Parar",
                    ["OK"] = "Val",
                    ["FocusModeActivated"] = "🎯 Mou Concentración Activáu",
                    ["FocusModeDeactivated"] = "🎯 Mou Concentración Desactiváu",
                    ["FocusModeDescription"] = "Interfaz simplificada pa concentrase.\nPrimi F11 pa salir.",
                    ["FocusModeRestored"] = "Interfaz completa restaurada.",
                    ["Warning"] = "Alvertencia",
                    ["Success"] = "Ésitu",
                    ["Error"] = "Fallu",
                    ["NoDocumentSelected"] = "Por favor seleiciona un documentu primero.",
                    ["FontSize"] = "📏 Tamañu de Lletra",
                    ["CurrentSize"] = "Tamañu actual: {0}pt",
                    ["PomodoroCompleted"] = "🍅 Pomodoro Completáu!",
                    ["PomodoroCompletedDescription"] = "¡Bon trabayu! Completasti una sesión de concentración de 25 minutos.\n\n¿Ye hora d'un descansu de 5 minutos?",
                    ["StartBreak"] = "Entamar Descansu",
                    ["ContinueWriting"] = "Siguir Escribiendo",
                    ["Close"] = "Zarrar",
                    ["AdvancedSearch"] = "Busca Avanzada",
                    ["SearchFor"] = "Guetar:",
                    ["SearchIn"] = "Guetar en:",
                    ["CurrentDocument"] = "Documentu Actual",
                    ["AllDocuments"] = "Tolos Documentos",
                    ["SelectedDocuments"] = "Documentos Escoyíos",
                    ["UseRegularExpressions"] = "Usar espresiones regulares",
                    ["WholeWordsOnly"] = "Namái pallabres completes",
                    ["FindAndReplace"] = "Guetar y Trocar",
                    ["Find"] = "Guetar:",
                    ["ReplaceWith"] = "Trocar con:",
                    ["CaseSensitive"] = "Distinguir mayúscules y minúscules",
                    ["ReplaceAll"] = "Trocar Too",
                    ["FindNext"] = "Guetar Siguiente",
                    ["SearchResult"] = "🔍 Resultáu de Busca",
                    ["FoundAtPosition"] = "Atopáu na posición {0}",
                    ["NotFound"] = "'{0}' non atopáu",
                    ["ReplacementsCompleted"] = "Realizáronse {0} trocamientos",
                    ["DocumentStatistics"] = "📊 Estadístiques del Documentu",
                    ["CompleteStatistics"] = "📊 Estadístiques Completes",
                    ["Content"] = "📝 Conteníu:",
                    ["Words"] = "• Pallabres: {0:N0}",
                    ["Characters"] = "• Carauteres: {0:N0}",
                    ["CharactersNoSpaces"] = "• Carauteres (ensin espacios): {0:N0}",
                    ["Lines"] = "• Llinies: {0:N0}",
                    ["Paragraphs"] = "• Párrafos: {0:N0}",
                    ["Sentences"] = "• Frases: {0:N0}",
                    ["AvgWordsPerSentence"] = "• Promediu pallabres/frase: {0}",
                    ["EstimatedTime"] = "⏱️ Tiempu Estimáu:",
                    ["ReadingTime"] = "• Tiempu de llectura: ~{0} min",
                    ["SpeakingTime"] = "• Tiempu d'oratoria: ~{0} min",
                    ["SessionStats"] = "📈 Estadístiques de Sesión:",
                    ["WordsWrittenToday"] = "• Pallabres escrites güei: {0:N0}",
                    ["WordsInSession"] = "• Pallabres nesta sesión: {0:N0}",
                    ["NoDocumentSelected"] = "Dengún Documentu Escoyíu",
                    ["NoDocumentSelectedDescription"] = "Por favor escueyi o cria un documentu enantes de xubilu a GitHub.",
                    ["Connected"] = "Coneutáu",
                    ["NotConnected"] = "Non Coneutáu",
                    ["LanguageChanged"] = "Idioma camudáu a {0}",
                    ["LastModified"] = "Última modificación",
                    ["DocumentIndex"] = "Índiz del Documentu",
                    ["WelcomeToJot"] = "Bienllegáu a Jot",
                    ["CreateFirstDocument"] = "Cria'l to primer documentu p'entamar",
                    ["CreateNewDocument"] = "Criar Documentu Nuevu",
                    ["GitHub"] = "GitHub",
                    ["ConnectGitHub"] = "Coneutar GitHub",
                    ["UploadCurrent"] = "Xubir Actual",
                    ["Repositories"] = "Repositorios",
                    ["Disconnect"] = "Desconeutar",
                    ["ExpandGitHubOptions"] = "Espander Opciones de GitHub",
                    ["DocumentTitle"] = "Títulu del documentu...",
                    ["SearchDocuments"] = "Guetar documentos...",
                    ["WordsCount"] = "Pallabres: {0}",
                    ["CharactersCount"] = "Carauteres: {0}",
                    ["ReadingTimeCount"] = "Tiempu de llectura: {0} min",
                    ["LineColumn"] = "Llinia {0}, Columna {1}",
                    ["ExportingToHtml"] = "Esportando a HTML...",
                    ["ToggleSidebar"] = "Alternar Barra Llateral",
                    ["QuickUploadToGitHub"] = "Xubida Rápida a GitHub",
                    ["GitHubSettings"] = "Configuración de GitHub",
                    ["AIAssistant"] = "Asistente IA",
                    ["PythonCodeExecution"] = "Execución de Códigu Python",
                    ["Close"] = "Zarrar",
                    ["Send"] = "Unviar",
                    ["EnterYourQuestion"] = "Escribi la to entruga...",
                    ["SuggestedQuestions"] = "Entrugues suxeríes:",
                    ["ExportDocument"] = "Esportar a HTML",
                    ["DeleteDocument"] = "Desaniciar",
                    ["UploadDocument"] = "Xubir a GitHub",
                    ["ChatbotWelcome"] = "¡Hola! Soi el to asistente de documentos. Pues entrugame sobro'l conteníu de los tos documentos.",
                    ["SendEmail"] = "Unviar per Correau",
                    ["Send"] = "Unviar",
                    ["Cancel"] = "Encaboxar",
                    ["ToEmail"] = "Pa (Email)",
                    ["FromEmail"] = "De (Email)",
                    ["SendMethod"] = "Métodu d'Unviamientu",
                    ["DefaultEmailClient"] = "Cliente de Correau Predetermináu",
                    ["CustomSMTP"] = "SMTP Personalizáu",
                    ["EmailFormat"] = "Formatu",
                    ["PlainText"] = "Testu Planu",
                    ["Password"] = "Contraseña",
                    ["SMTPServer"] = "Servidor SMTP",
                    ["EmailWarning"] = "Pa Gmail/Outlook, quiciabes necesites activar 'Accesu d'apps menos segures' o usar una contraseña d'aplicación.",
                    ["EmailSentSuccess"] = "¡Email unviáu correchu!",
                    ["EmailSentError"] = "Fallu al unviar email. Por favor verifica la to configuración.",
                    ["EnterEmail"] = "Por favor introduz una direición d'email válida.",
                    ["EmailClientOpened"] = "Cliente de correau abiertu correchu. Por favor completa l'unviamientu dende la to aplicación de correau.",
                    ["EnterCredentials"] = "Por favor introduz les tos credenciales d'email (correau y contraseña).",
                    ["PrintDocument"] = "Imprentar Documentu",
                    ["PrintError"] = "Fallu al imprentar el documentu. Por favor inténtalo otra vuelta.",

                    // 🔄 Historial de Versiones
                    ["VersionHistory"] = "Historial de Versiones",
                    ["Versions"] = "Versiones",
                    ["Restore"] = "Restaurar",
                    ["Details"] = "Detalles",
                    ["Preview"] = "Vista Previa",
                    ["CurrentVersion"] = "Versión actual",

                    // 🔐 Cifráu
                    ["EncryptDocument"] = "Cifrar Documentu",
                    ["UnlockDocument"] = "Desbloquiar Documentu",
                    ["ChangePassword"] = "Camudar Contraseña",
                    ["Encrypt"] = "Cifrar",
                    ["Unlock"] = "Desbloquiar",
                    ["Change"] = "Camudar",
                    ["CurrentPassword"] = "Contraseña Actual",
                    ["NewPassword"] = "Contraseña Nueva",
                    ["ConfirmPassword"] = "Confirmar Contraseña",
                    ["PasswordsDoNotMatch"] = "Les contraseñes nun coinciden",
                    ["EncryptDescription"] = "Protexe'l to documentu con una contraseña segura. Usa cifráu AES-256.",
                    ["UnlockDescription"] = "Introduz la to contraseña pa desbloquiar y ver esti documentu.",
                    ["ChangePasswordDescription"] = "Camuda la contraseña de cifráu d'esti documentu.",
                    ["EncryptionWarning"] = "⚠️ ¡Recuerda la to contraseña! Nun hai manera de recuperala si la escaeces.",
                    ["EncryptionError"] = "Fallu de cifráu. Verifica la to contraseña ya inténtalo otra vuelta.",
                    ["LockDocument"] = "Bloquiar Documentu",

                    // ☁️ Sincronización
                    ["CloudSync"] = "Sincronización na Ñube",
                    ["CloudProvider"] = "Fornidor de Ñube",
                    ["AutoSync"] = "Sincronización Automática",
                    ["Enabled"] = "Activáu",
                    ["Disabled"] = "Desactiváu",
                    ["LastSync"] = "Última sincronización",
                    ["NeverSynced"] = "Enxamás sincronizáu",
                    ["SyncNow"] = "Sincronizar Agora",
                    ["Syncing"] = "Sincronizando...",
                    ["SelectProvider"] = "Escueyi un fornidor de ñube",
                    ["SyncSuccess"] = "Sincronizáu correchu",
                    ["SyncError"] = "Fallu de sincronización",
                    ["CloudSyncInfo"] = "El to documentu sincronizaráse automáticamente col fornidor de ñube escoyíu.",

                    // 📸 OCR
                    ["OCR"] = "OCR - Reconocimientu de Testu",
                    ["OCRDescription"] = "Estrayi testu d'imáxenes usando reconocimientu ópticu de carauteres.",
                    ["OCRLanguage"] = "Idioma OCR",
                    ["SelectImage"] = "Esbillar Imaxe",
                    ["FromClipboard"] = "Dende'l Porta-retayos",
                    ["ExtractedText"] = "Testu Estrayíu",
                    ["NoTextExtracted"] = "Entá nun s'estrayó testu...",
                    ["ExtractingText"] = "Estrayendo testu...",
                    ["TextExtracted"] = "Testu estrayíu correchu",
                    ["NoImageInClipboard"] = "Nun hai imaxe nel porta-retayos",
                    ["NoTextFound"] = "Nun s'atopó testu na imaxe",
                    ["InsertText"] = "Inxertar Testu",
                    ["Characters"] = "carauteres",

                    // 🔗 Enllaces
                    ["DocumentLinks"] = "Enllaces del Documentu",
                    ["OutgoingLinks"] = "Enllaces Salientes",
                    ["Backlinks"] = "Retroenlaces",
                    ["RelatedDocuments"] = "Documentos Rellacionaos",
                    ["BrokenLinks"] = "Enllaces Rotos",
                    ["WikiLinkHelp"] = "Usa [[Nome Documentu]] pa criar enllaces ente documentos",
                    ["NoLinksFound"] = "Nun s'atoparon enllaces",
                    ["NoBacklinksFound"] = "Nun s'atoparon retroenlaces",
                    ["NoRelatedFound"] = "Nun s'atoparon documentos rellacionaos",
                    ["DocumentNotFound"] = "Documentu nun atopáu",
                    ["NoBrokenLinks"] = "Nun hai enllaces rotos",

                    // 📎 Axuntos
                    ["Attachments"] = "Ficheros Axuntos",
                    ["AddFile"] = "Amestar Ficheru",
                    ["PasteImage"] = "Apegar Imaxe",
                    ["SelectAttachment"] = "Escueyi un axuntu pa previsualizar",
                    ["NoAttachments"] = "Entá nun hai axuntos",
                    ["OpenFile"] = "Abrir Ficheru",

                    // 🔧 Tooltips
                    ["TooltipNewDocument"] = "Documentu Nuevu",
                    ["TooltipSave"] = "Guardar",
                    ["TooltipExportHTML"] = "Esportar a HTML",
                    ["TooltipPrint"] = "Imprentar Documentu",
                    ["TooltipPython"] = "Execución de Códigu Python",
                    ["TooltipGitHubUpload"] = "Xubida Rápida a GitHub",
                    ["TooltipGitHubSettings"] = "Configuración de GitHub",
                    ["TooltipLanguage"] = "Idioma / Language",
                    ["TooltipAIAssistant"] = "Asistente IA",
                    ["TooltipSendEmail"] = "Unviar per Correau",
                    ["TooltipVersionHistory"] = "Historial de Versiones",
                    ["TooltipEncryption"] = "Cifráu",
                    ["TooltipCloudSync"] = "Sincronización na Ñube",
                    ["TooltipOCR"] = "OCR - Reconocimientu de Testu",
                    ["TooltipDocumentLinks"] = "Enllaces del Documentu",
                    ["TooltipAttachments"] = "Ficheros Axuntos"
                }
            };
        }

        public void SetLanguage(string languageCode)
        {
            try
            {
                if (!_supportedLanguages.ContainsKey(languageCode))
                {
                    languageCode = "en";
                }

                CurrentLanguage = languageCode;

                // Notificar cambio global para forzar actualización de todas las propiedades
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));

                // Notificar cambios específicos
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(CurrentLanguage)));
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(CurrentLanguageName)));

                System.Diagnostics.Debug.WriteLine($"Language changed to: {languageCode} ({CurrentLanguageName})");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Error setting language: {ex.Message}");
            }
        }

        public string GetString(string key)
        {
            try
            {
                if (_localizedStrings != null && 
                    _localizedStrings.TryGetValue(CurrentLanguage, out var languageDict) &&
                    languageDict.TryGetValue(key, out var value))
                {
                    return value;
                }

                // Fallback a inglés si no se encuentra en el idioma actual
                if (_localizedStrings != null && 
                    _localizedStrings.TryGetValue("en", out var englishDict) &&
                    englishDict.TryGetValue(key, out var englishValue))
                {
                    return englishValue;
                }

                return key;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Error getting string for key '{key}': {ex.Message}");
                return key;
            }
        }

        public string GetString(string key, params object[] args)
        {
            try
            {
                var format = GetString(key);
                return string.Format(format, args);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Error formatting string for key '{key}': {ex.Message}");
                return key;
            }
        }
    }
}